# coding: utf-8

"""
    VxRail Disk and Cluster Management

    APIs for disk and cluster management  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vxrail_ansible_utility
from vxrail_ansible_utility.models.layer3_expansion_validation_two_vds_request import Layer3ExpansionValidationTwoVDSRequest  # noqa: E501
from vxrail_ansible_utility.rest import ApiException


class TestLayer3ExpansionValidationTwoVDSRequest(unittest.TestCase):
    """Layer3ExpansionValidationTwoVDSRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLayer3ExpansionValidationTwoVDSRequest(self):
        """Test Layer3ExpansionValidationTwoVDSRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vxrail_ansible_utility.models.layer3_expansion_validation_two_vds_request.Layer3ExpansionValidationTwoVDSRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
