# coding: utf-8

"""
    VxRail Disk and Cluster Management

    APIs for disk and cluster management  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vxrail_ansible_utility
from vxrail_ansible_utility.api.cluster_information_api import ClusterInformationApi  # noqa: E501
from vxrail_ansible_utility.rest import ApiException


class TestClusterInformationApi(unittest.TestCase):
    """ClusterInformationApi unit test stubs"""

    def setUp(self):
        self.api = ClusterInformationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_private_cluster_network_nsxt_get(self):
        """Test case for private_cluster_network_nsxt_get

        Get NSX-T network information.  # noqa: E501
        """
        pass

    def test_v1_cluster_get(self):
        """Test case for v1_cluster_get

        Retrieves VxRail cluster information.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
