# coding: utf-8

"""
    VxRail Disk and Cluster Management

    APIs for disk and cluster management  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vxrail_ansible_utility
from vxrail_ansible_utility.api.virtual_machine_information_api import VirtualMachineInformationApi  # noqa: E501
from vxrail_ansible_utility.rest import ApiException


class TestVirtualMachineInformationApi(unittest.TestCase):
    """VirtualMachineInformationApi unit test stubs"""

    def setUp(self):
        self.api = VirtualMachineInformationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_cluster_system_virtual_machines_get(self):
        """Test case for v1_cluster_system_virtual_machines_get

        Retrieves information about system virtual machines in the cluster.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
