# coding: utf-8

"""
    VxRail Disk and Cluster Management

    APIs for disk and cluster management  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vxrail_ansible_utility
from vxrail_ansible_utility.api.node_expansion_status_pre_check_api import NodeExpansionStatusPreCheckApi  # noqa: E501
from vxrail_ansible_utility.rest import ApiException


class TestNodeExpansionStatusPreCheckApi(unittest.TestCase):
    """NodeExpansionStatusPreCheckApi unit test stubs"""

    def setUp(self):
        self.api = NodeExpansionStatusPreCheckApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_private_cluster_expansion_layer3_precheck_post(self):
        """Test case for private_cluster_expansion_layer3_precheck_post

        Start a L3 cluster expansion job based on the provided specs  # noqa: E501
        """
        pass

    def test_private_cluster_expansion_precheck_post(self):
        """Test case for private_cluster_expansion_precheck_post

        Start a cluster expansion job based on the provided specs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
