# coding: utf-8

"""
    VxRail Disk and Cluster Management

    APIs for disk and cluster management  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vxrail_ansible_utility
from vxrail_ansible_utility.api.disk_led_api import DiskLEDApi  # noqa: E501
from vxrail_ansible_utility.rest import ApiException


class TestDiskLEDApi(unittest.TestCase):
    """DiskLEDApi unit test stubs"""

    def setUp(self):
        self.api = DiskLEDApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_private_disks_disk_sn_led_put(self):
        """Test case for private_disks_disk_sn_led_put

        change sepcific disk led status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
