# coding: utf-8

"""
    VxRail Disk and Cluster Management

    APIs for disk and cluster management  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vxrail_ansible_utility
from vxrail_ansible_utility.models.cluster_info import ClusterInfo  # noqa: E501
from vxrail_ansible_utility.rest import ApiException


class TestClusterInfo(unittest.TestCase):
    """ClusterInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterInfo(self):
        """Test ClusterInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vxrail_ansible_utility.models.cluster_info.ClusterInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
