# coding: utf-8

"""
    VxRail Disk and Cluster Management

    APIs for disk and cluster management  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vxrail_ansible_utility
from vxrail_ansible_utility.models.storage_info_slot_claims import StorageInfoSlotClaims  # noqa: E501
from vxrail_ansible_utility.rest import ApiException


class TestStorageInfoSlotClaims(unittest.TestCase):
    """StorageInfoSlotClaims unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageInfoSlotClaims(self):
        """Test StorageInfoSlotClaims"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vxrail_ansible_utility.models.storage_info_slot_claims.StorageInfoSlotClaims()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
