# coding: utf-8

"""
    VxRail Disk and Cluster Management

    APIs for disk and cluster management  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from vxrail_ansible_utility.api_client import ApiClient


class SegmentEntityManagementApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def private_v1_cluster_layer3_initial_segment_network_info_get(self, **kwargs):  # noqa: E501
        """Retrieves the intial rack node network configuration.  # noqa: E501

        Retrieves the intial rack node network configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.private_v1_cluster_layer3_initial_segment_network_info_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: Layer3SegmentSpec
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.private_v1_cluster_layer3_initial_segment_network_info_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.private_v1_cluster_layer3_initial_segment_network_info_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def private_v1_cluster_layer3_initial_segment_network_info_get_with_http_info(self, **kwargs):  # noqa: E501
        """Retrieves the intial rack node network configuration.  # noqa: E501

        Retrieves the intial rack node network configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.private_v1_cluster_layer3_initial_segment_network_info_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: Layer3SegmentSpec
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method private_v1_cluster_layer3_initial_segment_network_info_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/private/v1/cluster/layer3/initial-segment/network-info', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Layer3SegmentSpec',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def private_v1_cluster_layer3_segments_configured_hosts_count_get(self, **kwargs):  # noqa: E501
        """Get the count of configured hosts per segment.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.private_v1_cluster_layer3_segments_configured_hosts_count_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[SegmentHostStatisticsInfo]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.private_v1_cluster_layer3_segments_configured_hosts_count_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.private_v1_cluster_layer3_segments_configured_hosts_count_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def private_v1_cluster_layer3_segments_configured_hosts_count_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get the count of configured hosts per segment.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.private_v1_cluster_layer3_segments_configured_hosts_count_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[SegmentHostStatisticsInfo]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method private_v1_cluster_layer3_segments_configured_hosts_count_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/private/v1/cluster/layer3/segments/configured-hosts/count', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[SegmentHostStatisticsInfo]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v1_cluster_layer3_segment_post(self, body, **kwargs):  # noqa: E501
        """Creates a new segment.  # noqa: E501

        Creates a new segment.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_cluster_layer3_segment_post(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Layer3SegmentStartSpec body: Information about the segment configuration, including the proxy IP, gateway, netmask, VLAN, and topology. (required)
        :return: list[Model200]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.v1_cluster_layer3_segment_post_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.v1_cluster_layer3_segment_post_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def v1_cluster_layer3_segment_post_with_http_info(self, body, **kwargs):  # noqa: E501
        """Creates a new segment.  # noqa: E501

        Creates a new segment.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_cluster_layer3_segment_post_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Layer3SegmentStartSpec body: Information about the segment configuration, including the proxy IP, gateway, netmask, VLAN, and topology. (required)
        :return: list[Model200]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_cluster_layer3_segment_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `v1_cluster_layer3_segment_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/cluster/layer3/segment', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Model200]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v1_cluster_layer3_segment_segment_label_delete(self, segment_label, **kwargs):  # noqa: E501
        """Deletes a segment.  # noqa: E501

        Deletes a segment.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_cluster_layer3_segment_segment_label_delete(segment_label, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str segment_label: The label of the current segment to be acted upon. (required)
        :return: list[Model200]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.v1_cluster_layer3_segment_segment_label_delete_with_http_info(segment_label, **kwargs)  # noqa: E501
        else:
            (data) = self.v1_cluster_layer3_segment_segment_label_delete_with_http_info(segment_label, **kwargs)  # noqa: E501
            return data

    def v1_cluster_layer3_segment_segment_label_delete_with_http_info(self, segment_label, **kwargs):  # noqa: E501
        """Deletes a segment.  # noqa: E501

        Deletes a segment.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_cluster_layer3_segment_segment_label_delete_with_http_info(segment_label, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str segment_label: The label of the current segment to be acted upon. (required)
        :return: list[Model200]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['segment_label']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_cluster_layer3_segment_segment_label_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'segment_label' is set
        if ('segment_label' not in params or
                params['segment_label'] is None):
            raise ValueError("Missing the required parameter `segment_label` when calling `v1_cluster_layer3_segment_segment_label_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'segment_label' in params:
            path_params['segment-label'] = params['segment_label']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/cluster/layer3/segment/{segment-label}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Model200]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v1_cluster_layer3_segment_segment_label_get(self, segment_label, **kwargs):  # noqa: E501
        """Retrieves the segment configuration for a specific segment.  # noqa: E501

        Retrieves the segment configuration for a specific segment.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_cluster_layer3_segment_segment_label_get(segment_label, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str segment_label: The label of the current segment to be acted upon. (required)
        :return: Layer3SegmentSpec
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.v1_cluster_layer3_segment_segment_label_get_with_http_info(segment_label, **kwargs)  # noqa: E501
        else:
            (data) = self.v1_cluster_layer3_segment_segment_label_get_with_http_info(segment_label, **kwargs)  # noqa: E501
            return data

    def v1_cluster_layer3_segment_segment_label_get_with_http_info(self, segment_label, **kwargs):  # noqa: E501
        """Retrieves the segment configuration for a specific segment.  # noqa: E501

        Retrieves the segment configuration for a specific segment.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_cluster_layer3_segment_segment_label_get_with_http_info(segment_label, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str segment_label: The label of the current segment to be acted upon. (required)
        :return: Layer3SegmentSpec
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['segment_label']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_cluster_layer3_segment_segment_label_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'segment_label' is set
        if ('segment_label' not in params or
                params['segment_label'] is None):
            raise ValueError("Missing the required parameter `segment_label` when calling `v1_cluster_layer3_segment_segment_label_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'segment_label' in params:
            path_params['segment-label'] = params['segment_label']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/cluster/layer3/segment/{segment-label}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Layer3SegmentSpec',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v1_cluster_layer3_segment_segment_label_health_get(self, segment_label, **kwargs):  # noqa: E501
        """Retrieves the health status for a specific segment.  # noqa: E501

        Retrieves the health status for a specific segment.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_cluster_layer3_segment_segment_label_health_get(segment_label, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str segment_label: The label of the segment that you want to query. (required)
        :return: list[SegmentStatusInfo]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.v1_cluster_layer3_segment_segment_label_health_get_with_http_info(segment_label, **kwargs)  # noqa: E501
        else:
            (data) = self.v1_cluster_layer3_segment_segment_label_health_get_with_http_info(segment_label, **kwargs)  # noqa: E501
            return data

    def v1_cluster_layer3_segment_segment_label_health_get_with_http_info(self, segment_label, **kwargs):  # noqa: E501
        """Retrieves the health status for a specific segment.  # noqa: E501

        Retrieves the health status for a specific segment.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_cluster_layer3_segment_segment_label_health_get_with_http_info(segment_label, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str segment_label: The label of the segment that you want to query. (required)
        :return: list[SegmentStatusInfo]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['segment_label']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_cluster_layer3_segment_segment_label_health_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'segment_label' is set
        if ('segment_label' not in params or
                params['segment_label'] is None):
            raise ValueError("Missing the required parameter `segment_label` when calling `v1_cluster_layer3_segment_segment_label_health_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'segment_label' in params:
            path_params['segment-label'] = params['segment_label']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/cluster/layer3/segment/{segment-label}/health', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[SegmentStatusInfo]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v1_cluster_layer3_segment_segment_label_patch(self, body, segment_label, **kwargs):  # noqa: E501
        """Changes the segment label for the current segment.  # noqa: E501

        Changes the segment label for the current segment.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_cluster_layer3_segment_segment_label_patch(body, segment_label, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Body1 body: The new label that you want the segment to be changed to. (required)
        :param str segment_label: The label of the current segment to be acted upon. (required)
        :return: list[Model200]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.v1_cluster_layer3_segment_segment_label_patch_with_http_info(body, segment_label, **kwargs)  # noqa: E501
        else:
            (data) = self.v1_cluster_layer3_segment_segment_label_patch_with_http_info(body, segment_label, **kwargs)  # noqa: E501
            return data

    def v1_cluster_layer3_segment_segment_label_patch_with_http_info(self, body, segment_label, **kwargs):  # noqa: E501
        """Changes the segment label for the current segment.  # noqa: E501

        Changes the segment label for the current segment.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_cluster_layer3_segment_segment_label_patch_with_http_info(body, segment_label, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Body1 body: The new label that you want the segment to be changed to. (required)
        :param str segment_label: The label of the current segment to be acted upon. (required)
        :return: list[Model200]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'segment_label']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_cluster_layer3_segment_segment_label_patch" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `v1_cluster_layer3_segment_segment_label_patch`")  # noqa: E501
        # verify the required parameter 'segment_label' is set
        if ('segment_label' not in params or
                params['segment_label'] is None):
            raise ValueError("Missing the required parameter `segment_label` when calling `v1_cluster_layer3_segment_segment_label_patch`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'segment_label' in params:
            path_params['segment-label'] = params['segment_label']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/cluster/layer3/segment/{segment-label}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Model200]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v1_cluster_layer3_segment_segment_label_post(self, body, segment_label, **kwargs):  # noqa: E501
        """Updates the segment configuration for a specific segment.  # noqa: E501

        Updates the segment configuration for a specific segment.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_cluster_layer3_segment_segment_label_post(body, segment_label, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Layer3SegmentStartSpec body: Information about the segment configuration, including the proxy IP, gateway, netmask, VLAN, and topology. (required)
        :param str segment_label: The label of the current segment to be acted upon. (required)
        :return: list[Model200]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.v1_cluster_layer3_segment_segment_label_post_with_http_info(body, segment_label, **kwargs)  # noqa: E501
        else:
            (data) = self.v1_cluster_layer3_segment_segment_label_post_with_http_info(body, segment_label, **kwargs)  # noqa: E501
            return data

    def v1_cluster_layer3_segment_segment_label_post_with_http_info(self, body, segment_label, **kwargs):  # noqa: E501
        """Updates the segment configuration for a specific segment.  # noqa: E501

        Updates the segment configuration for a specific segment.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_cluster_layer3_segment_segment_label_post_with_http_info(body, segment_label, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Layer3SegmentStartSpec body: Information about the segment configuration, including the proxy IP, gateway, netmask, VLAN, and topology. (required)
        :param str segment_label: The label of the current segment to be acted upon. (required)
        :return: list[Model200]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'segment_label']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_cluster_layer3_segment_segment_label_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `v1_cluster_layer3_segment_segment_label_post`")  # noqa: E501
        # verify the required parameter 'segment_label' is set
        if ('segment_label' not in params or
                params['segment_label'] is None):
            raise ValueError("Missing the required parameter `segment_label` when calling `v1_cluster_layer3_segment_segment_label_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'segment_label' in params:
            path_params['segment-label'] = params['segment_label']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/cluster/layer3/segment/{segment-label}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Model200]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v1_cluster_layer3_segments_get(self, **kwargs):  # noqa: E501
        """Retrieves a list of layer 3 segments that are recognized by VxRail Manager.  # noqa: E501

        Retrieves a list of layer 3 segments that are recognized by VxRail Manager.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_cluster_layer3_segments_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[str]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.v1_cluster_layer3_segments_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.v1_cluster_layer3_segments_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def v1_cluster_layer3_segments_get_with_http_info(self, **kwargs):  # noqa: E501
        """Retrieves a list of layer 3 segments that are recognized by VxRail Manager.  # noqa: E501

        Retrieves a list of layer 3 segments that are recognized by VxRail Manager.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_cluster_layer3_segments_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[str]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_cluster_layer3_segments_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/cluster/layer3/segments', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[str]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
