shared:
  environments:
    CI: true
    
pipelines:
  - kind: linters.commit
    name: lint commit
    useLocal: true
    events:
      - pull_request

  - kind: linters.python
    name: lint python
    useLocal: true
    events:
      - pull_request

  - kind: freestyle
    name: lint shell
    image: koalaman/shellcheck-alpine
    commands: |
      shellcheck scripts/*
    events:
      - pull_request
      - push
      

  - kind: freestyle
    name: lint and sanity test
    image: vxraildevops/vxrail-ansible
    commands: |
      export GITHUB_USER=$GITHUB_SERVICE_USER
      export GITHUB_API_TOKEN=$GITHUB_API_TOKEN
      export GITHUB_HOST="eos2git.cec.lab.emc.com"
      export UTILITY_REPO_URL="https://eos2git.cec.lab.emc.com/vxrail/ansible-vxrail-utility.git"
      export UTILITY_REPO_NAME="ansible-vxrail-utility"
      bash ./scripts/lint-ansible.sh
      bash ./scripts/sanity-test.sh
    events:
      - pull_request