---
- name: Add a node
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"
    vxm_version: "{{ vxm_version }}"
    host_psnt: "{{ host_psnt }}"
    hostname: "{{ hostname }}"
    mgt_account: "{{ mgt_account }}"
    mgt_passwd: "{{ mgt_passwd }}"
    root_passwd: "{{ root_passwd }}"
    mgt_ip: "{{ mgt_ip }}"
    vsan_ip: "{{ vsan_ip }}"
    vmotion_ip: "{{ vmotion_ip }}"
    mgt_ipv6: "{{ mgt_ipv6 }}"
    vsan_ipv6: "{{ vsan_ipv6 }}"
    vmotion_ipv6: "{{ vmotion_ipv6 }}"
    #Optional#
    rack_name_var: "{{ rack_name | default(omit) }}"
    order_number_var: "{{ order_number | default(omit) }}"

  tasks:
    - name: Start a cluster expansion
      dellemc.vxrail.dellemc_vxrail_cluster_expansion:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        vxm_version: "{{ vxm_version }}"
        host_psnt: "{{ host_psnt }}"
        hostname: "{{ hostname }}"
        mgt_account: "{{ mgt_account }}"
        mgt_passwd: "{{ mgt_passwd }}"
        root_passwd: "{{ root_passwd }}"
        mgt_ip: "{{ mgt_ip }}"
        vsan_ip: "{{ vsan_ip }}"
        vmotion_ip: "{{ vmotion_ip }}"
        mgt_ipv6: "{{ mgt_ipv6 }}"
        vsan_ipv6: "{{ vsan_ipv6 }}"
        vmotion_ipv6: "{{ vmotion_ipv6 }}"
        rack_name: "{{ rack_name_var }}"
        order_number: "{{ order_number_var }}"
        maintenance_mode: "{{ maintenance_mode | default(omit) }}"
        timeout: "{{ timeout | default(omit) }}"
        api_version_number: "{{ api_version_number | default(omit) }}"
      async: 1800
      poll: 0
      register: expansion_status
    - name: Check if cluster expansion job is completed...The node addition is still ongoing.
      async_status:
        jid: "{{ expansion_status.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 100
      delay: 30

    - name: Display added node host_psnt
      debug:
        var: host_psnt
    - name: Get Cluster Expansion Result
      debug:
        msg:  "{{job_result}}"
