---
- name: Retrieve Callhome Server Mode Information
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"

  tasks:
    - name: Get Callhome Mode Information
      dellemc.vxrail.dellemc_vxrail_callhome_getmode:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        timeout: "{{ timeout | default(omit) }}"
        api_version_number: "{{ api_version_number | default(omit) }}"
      register: callhome_mode

    - name: Display Callhome Mode Information
      debug:
        msg:  "{{callhome_mode}}"
