---
- name: Retrieve VxRail Chassis Information with v3/chassis API
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"

  tasks:
    - name: Get Chassis Information
      dellemc_vxrail_chassis_v3:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
      register: chassis_info

    - name: Display Chassis Information
      debug:
        msg:  "{{chassis_info}}"