---
- name: Retrieve Cluster Portgroup Information
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"
    node_fqdn: "{{ node_fqdn }}"

  tasks:
    - name: Get Node's Cluster Portgroup Information
      dellemc.vxrail.dellemc_vxrail_system_cluster_portgroups:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        node_fqdn: "{{ node_fqdn }}"
        timeout: "{{ timeout | default(omit) }}"
        api_version_number: "{{ api_version_number | default(omit) }}"
      register: cluster_portgroup_info

    - name: Display Cluster Portgroup Information
      debug:
        msg:  "{{ cluster_portgroup_info }}"
