---
- name: Retrieve VxRail Cluster Information
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"

  tasks:
    - name: Get Cluster Information
      dellemc_vxrail_clusterinfo:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
      register: cluster_info

    - name: Display Cluster Information
      debug:
        msg:  "{{cluster_info}}"
