---
- name: Unregister call home servers
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"

  tasks:
    - name: Disable call home servers
      dellemc.vxrail.dellemc_vxrail_callhome_disable:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        timeout: "{{ timeout | default(omit) }}"
        api_version_number: "{{ api_version_number | default(omit) }}"
      register: callhome_disable

    - name: Display Callhome Disabled Result
      debug:
        msg: "{{callhome_disable}}"
