---
- name: Retrieve VxRail Hosts Information with v5/hosts
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"

  tasks:
    - name: Get Hosts Information
      dellemc_vxrail_hosts_v5:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
      register: hosts_info

    - name: Display Hosts Information
      debug:
        msg:  "{{hosts_info}}"