---
- name: Retrieve VxRail iDRAC Users Information
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"
    sn: "{{ sn }}"

  tasks:
    - name: Get iDRAC Users
      dellemc.vxrail.dellemc_vxrail_idrac_getusers:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        sn: "{{ sn }}"
        timeout: "{{ timeout | default(omit) }}"
        api_version_number: "{{ api_version_number | default(omit) }}"
      register: iDRAC_Users
    - name: Display Idrac Users
      debug:
        msg:  "{{ iDRAC_Users }}"
