---
- name: Commit vLCM draft api
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"

  tasks:
    - name: Start to commit vLCM draft
      dellemc.vxrail.dellemc_vxrail_lcm_vlcm_commit_draft:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        api_version_number: "{{ api_version_number | default(omit) }}"
      register: job_result

    - name: Display vLCM commit draft result
      debug:
        msg: "{{ job_result }}"
