---
- name: Delete vLCM draft api
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"
    vc_root_account: "{{ vc_root_account }}"
    vc_root_passwd: "{{ vc_root_passwd }}"

  tasks:
    - name: Start to delete vLCM draft
      dellemc.vxrail.dellemc_vxrail_lcm_vlcm_delete_draft:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        vc_root_account: "{{ vc_root_account }}"
        vc_root_passwd: "{{ vc_root_passwd }}"
        api_version_number: "{{ api_version_number | default(omit) }}"
      register: job_result

    - name: Display vLCM delete draft result
      debug:
        msg: "{{ job_result }}"
