---
- name: LCM Precheck with v1 api
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"
    bundle_file_locator: "{{ bundle_file_locator }}"
    vc_root_account: "{{ vc_root_account }}"
    vc_root_passwd: "{{ vc_root_passwd }}"
    vxm_root_account: "{{ vxm_root_account }}"
    vxm_root_passwd: "{{ vxm_root_passwd }}"

  tasks:
    - name: Start to do LCM Precheck
      dellemc_vxrail_lcm_v1_precheck:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        bundle_file_locator: "{{ bundle_file_locator }}"
        vc_root_account: "{{ vc_root_account }}"
        vc_root_passwd: "{{ vc_root_passwd }}"
        vxm_root_account: "{{ vxm_root_account }}"
        vxm_root_passwd: "{{ vxm_root_passwd }}"
      async: 1800
      poll: 0
      register: lcm_precheck_status
    - name: Check if LCM Precheck is completed...The precheck is still ongoing.
      async_status:
        jid: "{{ lcm_precheck_status.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 100
      delay: 30
    - name: Get LCM Precheck Result
      debug:
        msg:  "{{job_result}}"