---
- name: LCM upgrade v1. Supported in VxRail versions 4.5.3xx+, 4.7.x, 7.0.x.
  hosts: localhost
  vars:
    ### Required ###
    vxmip_var: "{{ vxmip }}"
    vcadmin_var: "{{ vcadmin }}"
    vcpasswd_var: "{{ vcpasswd }}"
    bundle_var: "{{ bundle }}"
    vc_root_account_var: "{{ vc_root_account }}"
    vc_root_passwd_var: "{{ vc_root_passwd }}"
    vxm_root_account_var: "{{ vxm_root_account }}"
    vxm_root_passwd_var: "{{ vxm_root_passwd }}"
    ### Optional ###
    psc_root_account_var: "{{ psc_root_account | default(omit) }}"
    psc_root_passwd_var: "{{ psc_root_passwd | default(omit) }}"
    source_vcsa_host_name_var: "{{ source_vcsa_host_name | default(omit) }}"
    source_vcsa_host_user_name_var: "{{ source_vcsa_host_user_name | default(omit) }}"
    source_vcsa_host_user_passwd_var: "{{ source_vcsa_host_user_passwd | default(omit) }}"
    source_psc_host_name_var: "{{ source_psc_host_name | default(omit) }}"
    source_psc_host_user_name_var: "{{ source_psc_host_user_name | default(omit) }}"
    source_psc_host_user_passwd_var: "{{ source_psc_host_user_passwd | default(omit) }}"
    target_vcsa_host_name_var: "{{ target_vcsa_host_name | default(omit) }}"
    target_vcsa_host_user_name_var: "{{ target_vcsa_host_user_name | default(omit) }}"
    target_vcsa_host_user_passwd_var: "{{ target_vcsa_host_user_passwd | default(omit) }}"
    temporary_ip_var: "{{ temporary_ip | default(omit) }}"
    temporary_gateway_var: "{{ temporary_gateway | default(omit) }}"
    temporary_netmask_var: "{{ temporary_netmask | default(omit) }}"
    ### Optional for script, specify the API version to perform the upgrade. If not specified, the default value is the highest available version. ###
    api_version_number_var: "1"
    ### Optional for script, specify the timeout for the upgrade. If not specified, the default value is 6 hours. ###
    timeout_var: "{{ timeout | default(omit) }}"


  tasks:
    - name: Start to upgrade with v1
      dellemc_vxrail_lcm:
        vxmip: "{{ vxmip_var }}"
        vcadmin: "{{ vcadmin_var }}"
        vcpasswd: "{{ vcpasswd_var}}"
        bundle: "{{ bundle_var }}"
        vc_root_account: "{{ vc_root_account_var }}"
        vc_root_passwd: "{{ vc_root_passwd_var }}"
        vxm_root_account: "{{ vxm_root_account_var }}"
        vxm_root_passwd: "{{ vxm_root_passwd_var }}"
        api_version_number: "{{ api_version_number_var }}"
        timeout: "{{ timeout_var }}"
        psc_root_account: "{{ psc_root_account_var }}"
        psc_root_passwd: "{{ psc_root_passwd_var }}"
        source_vcsa_host_name: "{{ source_vcsa_host_name_var }}"
        source_vcsa_host_user_name: "{{ source_vcsa_host_user_name_var }}"
        source_vcsa_host_user_passwd: "{{ source_vcsa_host_user_passwd_var }}"
        source_psc_host_name: "{{ source_psc_host_name_var }}"
        source_psc_host_user_name: "{{ source_psc_host_user_name_var }}"
        source_psc_host_user_passwd: "{{ source_psc_host_user_passwd_var }}"
        target_vcsa_host_name: "{{ target_vcsa_host_name_var }}"
        target_vcsa_host_user_name: "{{ target_vcsa_host_user_name_var }}"
        target_vcsa_host_user_passwd: "{{ target_vcsa_host_user_passwd_var }}"
        temporary_ip: "{{ temporary_ip_var }}"
        temporary_gateway: "{{ temporary_gateway_var }}"
        temporary_netmask: "{{ temporary_netmask_var }}"
      async: 25200
      poll: 0
      register: lcm_status
    - name: Check if LCM is completed...The upgrade is still ongoing.
      async_status:
        jid: "{{ lcm_status.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 210
      delay: 120
    - name: Get LCM Result
      debug:
        msg:  "{{job_result}}"

