---
- name: Retrieve VxRail Management Account Information
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"

  tasks:
    - name: Retrieve VxRail Management Account Info (VC Only)
      dellemc_vxrail_system_get_management_accounts:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        api_version_number: "{{ api_version_number | default(omit) }}"
        timeout: "{{ timeout | default(omit) }}"
      register: accounts_info

    - name: Display VxRail Management Account Info (VC Only)
      debug:
        msg:  "{{accounts_info}}"
