---
- name: Retrieve VxRail System Precheck Profiles
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"

  tasks:
    - name: Get System Precheck Profiles Information
      dellemc.vxrail.dellemc_vxrail_system_getprecheckprofiles:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        timeout: "{{ timeout | default(omit) }}"
        api_version_number: "{{ api_version_number | default(omit) }}"
      register: precheck_profiles

    - name: Display System Precheck Profiles Information
      debug:
        msg:  "{{precheck_profiles}}"
