---
- name: Retrieve VxRail System Proxy Information
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"

  tasks:
    - name: Get VxRail System Proxy Information
      dellemc.vxrail.dellemc_vxrail_system_get_proxy:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        api_version_number: "{{ api_version_number | default(omit) }}"
        timeout: "{{ timeout | default(omit) }}"
      register: proxy_info

    - name: Display VxRail System Proxy Information
      debug:
        msg:  "{{proxy_info}}"
