---
- name: Remove a node
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"
    host_sn: "{{ host_sn }}"
    vc_root_account: "{{ vc_root_account }}"
    vc_root_passwd: "{{ vc_root_passwd }}"

  tasks:
    - name: Start to remove node
      dellemc_vxrail_cluster_rmhost_v1:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        host_sn: "{{ host_sn }}"
        vc_root_account: "{{ vc_root_account }}"
        vc_root_passwd: "{{ vc_root_passwd }}"
      async: 1800
      poll: 0
      register: removal_status
    - name: Check if Node Removal job is completed...The node removal is still ongoing.
      async_status:
        jid: "{{ removal_status.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 100
      delay: 30

    - name: Display removed node host_sn
      debug:
        var: host_sn
    - name: Get Node Removal Result
      debug:
        msg:  "{{job_result}}"