---
- name: Retrieve VxRail System DNS Information
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"

  tasks:
    - name: Get System DNS Information
      dellemc_vxrail_system_getdns_v1:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
      register: system_dns_info

    - name: Display System DNS Information
      debug:
        msg:  "{{system_dns_info}}"