---
- name: Update system credential
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"
    component: "{{ component }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"

  tasks:
    - name: Update the management user passwords
      dellemc.vxrail.dellemc_vxrail_system_update_credential:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        component: "{{ component }}"
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        timeout: "{{ timeout | default(omit) }}"
        api_version_number: "{{ api_version_number | default(omit) }}"
      register: system_update_credential

    - name: Display the management user passwords change
      debug:
        msg:  "{{ system_update_credential }}"
