---
- name: Retrieve VxRail System NTP Information
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"

  tasks:
    - name: Get System NTP Information
      dellemc.vxrail.dellemc_vxrail_system_get_ntp:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        api_version_number: "{{ api_version_number | default(omit) }}"
        timeout: "{{ timeout | default(omit) }}"
      register: system_ntp_info

    - name: Display System NTP Information
      debug:
        msg:  "{{system_ntp_info}}"
