---
- name: Retrieve VxRail Cluster Hosts Information
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"

  tasks:
    - name: Get Cluster Hosts Information
      dellemc.vxrail.dellemc_vxrail_system_getclusterhosts:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        timeout: "{{ timeout | default(omit) }}"
        api_version_number: "{{ api_version_number | default(omit) }}"
      register: hosts_info

    - name: Display Cluster Hosts Information
      debug:
        msg:  "{{hosts_info}}"