---
- name: Validate VxRail Credential Information
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"
    #Optional
    vc_root_account_var: "{{ vc_root_account  | default(omit)  }}"
    vc_root_passwd_var: "{{ vc_root_passwd  | default(omit)  }}"
    psc_root_account_var: "{{ psc_root_account  | default(omit)  }}"
    psc_root_passwd_var: "{{ psc_root_passwd  | default(omit)  }}"
    host_sn_var: "{{ host_sn  | default(omit)  }}"
    host_root_account_var: "{{ host_root_account  | default(omit)  }}"
    host_root_passwd_var: "{{ host_root_passwd  | default(omit)  }}"


  tasks:
    - name: Validate VxRail Credential Information
      dellemc.vxrail.dellemc_vxrail_system_validate_credential:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        vc_root_account: "{{ vc_root_account_var }}"
        vc_root_passwd: "{{ vc_root_passwd_var }}"
        psc_root_account: "{{ psc_root_account_var }}"
        psc_root_passwd: "{{ psc_root_passwd_var }}"
        host_sn: "{{ host_sn_var }}"
        host_root_account: "{{ host_root_account_var }}"
        host_root_passwd: "{{ host_root_passwd_var }}"
        timeout: "{{ timeout | default(omit) }}"
        api_version_number: "{{ api_version_number | default(omit) }}"
      register: Result

    - name: Display Validate VxRail Credential Information
      debug:
        msg:  "{{Result}}"
