---
- name: Update system credential
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"
    component: "{{ component }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password  | default(omit) }}"
    current_password: "{{ current_password | default(omit) }}"
    new_password: "{{ new_password | default(omit) }}"
    api_version_number: "{{ api_version_number | default(3) }}"

  tasks:
    - name: Update the management user passwords
      dellemc_vxrail_system_update_credential:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        component: "{{ component }}"
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password if (api_version_number | int) < 3 else omit }}"
        current_password: "{{ current_password if (api_version_number | int) >= 3 else omit }}"
        new_password: "{{ new_password if (api_version_number | int) >= 3 else omit }}"
        timeout: "{{ timeout | default(omit) }}"
        api_version_number: "{{ api_version_number }}"
      register: system_update_credential
