---
- name: Upload advisory meta bundle
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"
    meta_bundle: "{{ meta_bundle }}"

  tasks:
    - name: Start to upload advisory meta bundle
      dellemc.vxrail.dellemc_vxrail_lcm_advisory_meta_bundle:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        meta_bundle: "{{ meta_bundle }}"
        timeout: "{{ timeout | default(omit) }}"
        api_version_number: "{{ api_version_number | default(omit) }}"
      register: upload_advisory_meta_bundle

    - name: Display advisory meta bundle Result
      debug:
        msg: "{{upload_advisory_meta_bundle}}"
