---
- name: Retrieve VxRail VC Mode Information
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"

  tasks:
    - name: Get VC Mode Information
      dellemc_vxrail_vc_getmode_v1:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
      register: vc_mode_info

    - name: Display VC Mode Info
      debug:
        msg:  "{{vc_mode_info}}"
