---
- name: Retrives name, status and host information for system virtual machines in the VxRail cluster
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"

  tasks:
    - name: Get System VM Information
      dellemc_vxrail_cluster_getvm_v1:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
      register: system_vm_info

    - name: Display System VM Information
      debug:
        msg:  "{{system_vm_info}}"
