---
- name: Retrieves name, status and host information for system virtual machines in the VxRail cluster
  hosts: localhost
  vars:
    vxmip: "{{ vxmip }}"
    vcadmin: "{{ vcadmin }}"
    vcpasswd: "{{ vcpasswd }}"

  tasks:
    - name: Get System VM Information
      dellemc_vxrail_cluster_getvm:
        vxmip: "{{ vxmip }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        timeout: "{{ timeout | default(omit) }}"
        api_version_number: "{{ api_version_number | default(omit) }}"
      register: system_vm_info

    - name: Display System VM Information
      debug:
        msg:  "{{system_vm_info}}"
