# coding: utf-8

"""
    VxRail Disk and Cluster Management

    APIs for disk and cluster management  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Body3(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'management_ip': 'str',
        'segment_label': 'str'
    }

    attribute_map = {
        'management_ip': 'managementIp',
        'segment_label': 'segmentLabel'
    }

    def __init__(self, management_ip=None, segment_label=None):  # noqa: E501
        """Body3 - a model defined in Swagger"""  # noqa: E501
        self._management_ip = None
        self._segment_label = None
        self.discriminator = None
        if management_ip is not None:
            self.management_ip = management_ip
        if segment_label is not None:
            self.segment_label = segment_label

    @property
    def management_ip(self):
        """Gets the management_ip of this Body3.  # noqa: E501


        :return: The management_ip of this Body3.  # noqa: E501
        :rtype: str
        """
        return self._management_ip

    @management_ip.setter
    def management_ip(self, management_ip):
        """Sets the management_ip of this Body3.


        :param management_ip: The management_ip of this Body3.  # noqa: E501
        :type: str
        """

        self._management_ip = management_ip

    @property
    def segment_label(self):
        """Gets the segment_label of this Body3.  # noqa: E501


        :return: The segment_label of this Body3.  # noqa: E501
        :rtype: str
        """
        return self._segment_label

    @segment_label.setter
    def segment_label(self, segment_label):
        """Sets the segment_label of this Body3.


        :param segment_label: The segment_label of this Body3.  # noqa: E501
        :type: str
        """

        self._segment_label = segment_label

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body3, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body3):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
