# coding: utf-8

"""
    VxRail Disk and Cluster Management

    APIs for disk and cluster management  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClusterMigrationNameSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'current_name': 'str',
        'new_name': 'str'
    }

    attribute_map = {
        'current_name': 'current_name',
        'new_name': 'new_name'
    }

    def __init__(self, current_name=None, new_name=None):  # noqa: E501
        """ClusterMigrationNameSpec - a model defined in Swagger"""  # noqa: E501
        self._current_name = None
        self._new_name = None
        self.discriminator = None
        self.current_name = current_name
        self.new_name = new_name

    @property
    def current_name(self):
        """Gets the current_name of this ClusterMigrationNameSpec.  # noqa: E501


        :return: The current_name of this ClusterMigrationNameSpec.  # noqa: E501
        :rtype: str
        """
        return self._current_name

    @current_name.setter
    def current_name(self, current_name):
        """Sets the current_name of this ClusterMigrationNameSpec.


        :param current_name: The current_name of this ClusterMigrationNameSpec.  # noqa: E501
        :type: str
        """
        if current_name is None:
            raise ValueError("Invalid value for `current_name`, must not be `None`")  # noqa: E501

        self._current_name = current_name

    @property
    def new_name(self):
        """Gets the new_name of this ClusterMigrationNameSpec.  # noqa: E501


        :return: The new_name of this ClusterMigrationNameSpec.  # noqa: E501
        :rtype: str
        """
        return self._new_name

    @new_name.setter
    def new_name(self, new_name):
        """Sets the new_name of this ClusterMigrationNameSpec.


        :param new_name: The new_name of this ClusterMigrationNameSpec.  # noqa: E501
        :type: str
        """
        if new_name is None:
            raise ValueError("Invalid value for `new_name`, must not be `None`")  # noqa: E501

        self._new_name = new_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClusterMigrationNameSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClusterMigrationNameSpec):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
