# coding: utf-8

"""
    VxRail Disk and Cluster Management

    APIs for disk and cluster management  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ExpansionPreviewHostInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'network': 'HostNetworkInfo',
        'is_layer3_proxy_node': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'network': 'network',
        'is_layer3_proxy_node': 'isLayer3ProxyNode'
    }

    def __init__(self, id=None, network=None, is_layer3_proxy_node=None):  # noqa: E501
        """ExpansionPreviewHostInfo - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._network = None
        self._is_layer3_proxy_node = None
        self.discriminator = None
        self.id = id
        self.network = network
        if is_layer3_proxy_node is not None:
            self.is_layer3_proxy_node = is_layer3_proxy_node

    @property
    def id(self):
        """Gets the id of this ExpansionPreviewHostInfo.  # noqa: E501


        :return: The id of this ExpansionPreviewHostInfo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ExpansionPreviewHostInfo.


        :param id: The id of this ExpansionPreviewHostInfo.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def network(self):
        """Gets the network of this ExpansionPreviewHostInfo.  # noqa: E501


        :return: The network of this ExpansionPreviewHostInfo.  # noqa: E501
        :rtype: HostNetworkInfo
        """
        return self._network

    @network.setter
    def network(self, network):
        """Sets the network of this ExpansionPreviewHostInfo.


        :param network: The network of this ExpansionPreviewHostInfo.  # noqa: E501
        :type: HostNetworkInfo
        """
        if network is None:
            raise ValueError("Invalid value for `network`, must not be `None`")  # noqa: E501

        self._network = network

    @property
    def is_layer3_proxy_node(self):
        """Gets the is_layer3_proxy_node of this ExpansionPreviewHostInfo.  # noqa: E501


        :return: The is_layer3_proxy_node of this ExpansionPreviewHostInfo.  # noqa: E501
        :rtype: bool
        """
        return self._is_layer3_proxy_node

    @is_layer3_proxy_node.setter
    def is_layer3_proxy_node(self, is_layer3_proxy_node):
        """Sets the is_layer3_proxy_node of this ExpansionPreviewHostInfo.


        :param is_layer3_proxy_node: The is_layer3_proxy_node of this ExpansionPreviewHostInfo.  # noqa: E501
        :type: bool
        """

        self._is_layer3_proxy_node = is_layer3_proxy_node

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExpansionPreviewHostInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExpansionPreviewHostInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
