# coding: utf-8

"""
    VxRail Disk and Cluster Management

    APIs for disk and cluster management  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HostDGInfoSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'host_serial_number': 'str',
        'customer_supplied': 'CSHostDGInfoSpec'
    }

    attribute_map = {
        'host_serial_number': 'host_serial_number',
        'customer_supplied': 'customer_supplied'
    }

    def __init__(self, host_serial_number=None, customer_supplied=None):  # noqa: E501
        """HostDGInfoSpec - a model defined in Swagger"""  # noqa: E501
        self._host_serial_number = None
        self._customer_supplied = None
        self.discriminator = None
        if host_serial_number is not None:
            self.host_serial_number = host_serial_number
        if customer_supplied is not None:
            self.customer_supplied = customer_supplied

    @property
    def host_serial_number(self):
        """Gets the host_serial_number of this HostDGInfoSpec.  # noqa: E501

        sn of host  # noqa: E501

        :return: The host_serial_number of this HostDGInfoSpec.  # noqa: E501
        :rtype: str
        """
        return self._host_serial_number

    @host_serial_number.setter
    def host_serial_number(self, host_serial_number):
        """Sets the host_serial_number of this HostDGInfoSpec.

        sn of host  # noqa: E501

        :param host_serial_number: The host_serial_number of this HostDGInfoSpec.  # noqa: E501
        :type: str
        """

        self._host_serial_number = host_serial_number

    @property
    def customer_supplied(self):
        """Gets the customer_supplied of this HostDGInfoSpec.  # noqa: E501


        :return: The customer_supplied of this HostDGInfoSpec.  # noqa: E501
        :rtype: CSHostDGInfoSpec
        """
        return self._customer_supplied

    @customer_supplied.setter
    def customer_supplied(self, customer_supplied):
        """Sets the customer_supplied of this HostDGInfoSpec.


        :param customer_supplied: The customer_supplied of this HostDGInfoSpec.  # noqa: E501
        :type: CSHostDGInfoSpec
        """

        self._customer_supplied = customer_supplied

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HostDGInfoSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HostDGInfoSpec):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
