# coding: utf-8

"""
    VxRail Disk and Cluster Management

    APIs for disk and cluster management  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Layer3VsanVmotionNetworkPreviewSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hosts': 'list[str]',
        'vsan_ips': 'list[str]',
        'vmotion_ips': 'list[str]'
    }

    attribute_map = {
        'hosts': 'hosts',
        'vsan_ips': 'vsanIps',
        'vmotion_ips': 'vmotionIps'
    }

    def __init__(self, hosts=None, vsan_ips=None, vmotion_ips=None):  # noqa: E501
        """Layer3VsanVmotionNetworkPreviewSpec - a model defined in Swagger"""  # noqa: E501
        self._hosts = None
        self._vsan_ips = None
        self._vmotion_ips = None
        self.discriminator = None
        self.hosts = hosts
        self.vsan_ips = vsan_ips
        self.vmotion_ips = vmotion_ips

    @property
    def hosts(self):
        """Gets the hosts of this Layer3VsanVmotionNetworkPreviewSpec.  # noqa: E501


        :return: The hosts of this Layer3VsanVmotionNetworkPreviewSpec.  # noqa: E501
        :rtype: list[str]
        """
        return self._hosts

    @hosts.setter
    def hosts(self, hosts):
        """Sets the hosts of this Layer3VsanVmotionNetworkPreviewSpec.


        :param hosts: The hosts of this Layer3VsanVmotionNetworkPreviewSpec.  # noqa: E501
        :type: list[str]
        """
        if hosts is None:
            raise ValueError("Invalid value for `hosts`, must not be `None`")  # noqa: E501

        self._hosts = hosts

    @property
    def vsan_ips(self):
        """Gets the vsan_ips of this Layer3VsanVmotionNetworkPreviewSpec.  # noqa: E501


        :return: The vsan_ips of this Layer3VsanVmotionNetworkPreviewSpec.  # noqa: E501
        :rtype: list[str]
        """
        return self._vsan_ips

    @vsan_ips.setter
    def vsan_ips(self, vsan_ips):
        """Sets the vsan_ips of this Layer3VsanVmotionNetworkPreviewSpec.


        :param vsan_ips: The vsan_ips of this Layer3VsanVmotionNetworkPreviewSpec.  # noqa: E501
        :type: list[str]
        """
        if vsan_ips is None:
            raise ValueError("Invalid value for `vsan_ips`, must not be `None`")  # noqa: E501

        self._vsan_ips = vsan_ips

    @property
    def vmotion_ips(self):
        """Gets the vmotion_ips of this Layer3VsanVmotionNetworkPreviewSpec.  # noqa: E501


        :return: The vmotion_ips of this Layer3VsanVmotionNetworkPreviewSpec.  # noqa: E501
        :rtype: list[str]
        """
        return self._vmotion_ips

    @vmotion_ips.setter
    def vmotion_ips(self, vmotion_ips):
        """Sets the vmotion_ips of this Layer3VsanVmotionNetworkPreviewSpec.


        :param vmotion_ips: The vmotion_ips of this Layer3VsanVmotionNetworkPreviewSpec.  # noqa: E501
        :type: list[str]
        """
        if vmotion_ips is None:
            raise ValueError("Invalid value for `vmotion_ips`, must not be `None`")  # noqa: E501

        self._vmotion_ips = vmotion_ips

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Layer3VsanVmotionNetworkPreviewSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Layer3VsanVmotionNetworkPreviewSpec):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
