# coding: utf-8

"""
    VxRail Disk and Cluster Management

    APIs for disk and cluster management  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Layer3SegmentOneInfoSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'required': 'list[str]',
        'optional': 'list[str]'
    }

    attribute_map = {
        'required': 'required',
        'optional': 'optional'
    }

    def __init__(self, required=None, optional=None):  # noqa: E501
        """Layer3SegmentOneInfoSpec - a model defined in Swagger"""  # noqa: E501
        self._required = None
        self._optional = None
        self.discriminator = None
        self.required = required
        self.optional = optional

    @property
    def required(self):
        """Gets the required of this Layer3SegmentOneInfoSpec.  # noqa: E501


        :return: The required of this Layer3SegmentOneInfoSpec.  # noqa: E501
        :rtype: list[str]
        """
        return self._required

    @required.setter
    def required(self, required):
        """Sets the required of this Layer3SegmentOneInfoSpec.


        :param required: The required of this Layer3SegmentOneInfoSpec.  # noqa: E501
        :type: list[str]
        """
        if required is None:
            raise ValueError("Invalid value for `required`, must not be `None`")  # noqa: E501
        allowed_values = ["MANAGEMENT", "VSAN", "VMOTION", "WITNESS"]  # noqa: E501
        if not set(required).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `required` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(required) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._required = required

    @property
    def optional(self):
        """Gets the optional of this Layer3SegmentOneInfoSpec.  # noqa: E501


        :return: The optional of this Layer3SegmentOneInfoSpec.  # noqa: E501
        :rtype: list[str]
        """
        return self._optional

    @optional.setter
    def optional(self, optional):
        """Sets the optional of this Layer3SegmentOneInfoSpec.


        :param optional: The optional of this Layer3SegmentOneInfoSpec.  # noqa: E501
        :type: list[str]
        """
        if optional is None:
            raise ValueError("Invalid value for `optional`, must not be `None`")  # noqa: E501
        allowed_values = ["MANAGEMENT", "VSAN", "VMOTION", "WITNESS"]  # noqa: E501
        if not set(optional).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `optional` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(optional) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._optional = optional

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Layer3SegmentOneInfoSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Layer3SegmentOneInfoSpec):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
