# coding: utf-8

"""
    VxRail Disk and Cluster Management

    APIs for disk and cluster management  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Layer3SegmentOneSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'vsan_gateway': 'str',
        'vmotion_gateway': 'str'
    }

    attribute_map = {
        'vsan_gateway': 'vsanGateway',
        'vmotion_gateway': 'vmotionGateway'
    }

    def __init__(self, vsan_gateway=None, vmotion_gateway=None):  # noqa: E501
        """Layer3SegmentOneSpec - a model defined in Swagger"""  # noqa: E501
        self._vsan_gateway = None
        self._vmotion_gateway = None
        self.discriminator = None
        self.vsan_gateway = vsan_gateway
        self.vmotion_gateway = vmotion_gateway

    @property
    def vsan_gateway(self):
        """Gets the vsan_gateway of this Layer3SegmentOneSpec.  # noqa: E501


        :return: The vsan_gateway of this Layer3SegmentOneSpec.  # noqa: E501
        :rtype: str
        """
        return self._vsan_gateway

    @vsan_gateway.setter
    def vsan_gateway(self, vsan_gateway):
        """Sets the vsan_gateway of this Layer3SegmentOneSpec.


        :param vsan_gateway: The vsan_gateway of this Layer3SegmentOneSpec.  # noqa: E501
        :type: str
        """
        if vsan_gateway is None:
            raise ValueError("Invalid value for `vsan_gateway`, must not be `None`")  # noqa: E501

        self._vsan_gateway = vsan_gateway

    @property
    def vmotion_gateway(self):
        """Gets the vmotion_gateway of this Layer3SegmentOneSpec.  # noqa: E501


        :return: The vmotion_gateway of this Layer3SegmentOneSpec.  # noqa: E501
        :rtype: str
        """
        return self._vmotion_gateway

    @vmotion_gateway.setter
    def vmotion_gateway(self, vmotion_gateway):
        """Sets the vmotion_gateway of this Layer3SegmentOneSpec.


        :param vmotion_gateway: The vmotion_gateway of this Layer3SegmentOneSpec.  # noqa: E501
        :type: str
        """
        if vmotion_gateway is None:
            raise ValueError("Invalid value for `vmotion_gateway`, must not be `None`")  # noqa: E501

        self._vmotion_gateway = vmotion_gateway

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Layer3SegmentOneSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Layer3SegmentOneSpec):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
