# coding: utf-8

"""
    VxRail Disk and Cluster Management

    APIs for disk and cluster management  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NodeAccount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'root': 'Account',
        'management': 'Account'
    }

    attribute_map = {
        'root': 'root',
        'management': 'management'
    }

    def __init__(self, root=None, management=None):  # noqa: E501
        """NodeAccount - a model defined in Swagger"""  # noqa: E501
        self._root = None
        self._management = None
        self.discriminator = None
        self.root = root
        self.management = management

    @property
    def root(self):
        """Gets the root of this NodeAccount.  # noqa: E501


        :return: The root of this NodeAccount.  # noqa: E501
        :rtype: Account
        """
        return self._root

    @root.setter
    def root(self, root):
        """Sets the root of this NodeAccount.


        :param root: The root of this NodeAccount.  # noqa: E501
        :type: Account
        """
        if root is None:
            raise ValueError("Invalid value for `root`, must not be `None`")  # noqa: E501

        self._root = root

    @property
    def management(self):
        """Gets the management of this NodeAccount.  # noqa: E501


        :return: The management of this NodeAccount.  # noqa: E501
        :rtype: Account
        """
        return self._management

    @management.setter
    def management(self, management):
        """Sets the management of this NodeAccount.


        :param management: The management of this NodeAccount.  # noqa: E501
        :type: Account
        """
        if management is None:
            raise ValueError("Invalid value for `management`, must not be `None`")  # noqa: E501

        self._management = management

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NodeAccount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NodeAccount):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
