# coding: utf-8

"""
    VxRail Disk and Cluster Management

    APIs for disk and cluster management  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NodePreCheckRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'nodes': 'list[str]',
        'customer_supplied_nodes': 'list[CustomerSuppliedSpec]',
        'segment_label': 'str'
    }

    attribute_map = {
        'nodes': 'nodes',
        'customer_supplied_nodes': 'customer_supplied_nodes',
        'segment_label': 'segmentLabel'
    }

    def __init__(self, nodes=None, customer_supplied_nodes=None, segment_label=None):  # noqa: E501
        """NodePreCheckRequest - a model defined in Swagger"""  # noqa: E501
        self._nodes = None
        self._customer_supplied_nodes = None
        self._segment_label = None
        self.discriminator = None
        if nodes is not None:
            self.nodes = nodes
        if customer_supplied_nodes is not None:
            self.customer_supplied_nodes = customer_supplied_nodes
        if segment_label is not None:
            self.segment_label = segment_label

    @property
    def nodes(self):
        """Gets the nodes of this NodePreCheckRequest.  # noqa: E501

        The serial number of node  # noqa: E501

        :return: The nodes of this NodePreCheckRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._nodes

    @nodes.setter
    def nodes(self, nodes):
        """Sets the nodes of this NodePreCheckRequest.

        The serial number of node  # noqa: E501

        :param nodes: The nodes of this NodePreCheckRequest.  # noqa: E501
        :type: list[str]
        """

        self._nodes = nodes

    @property
    def customer_supplied_nodes(self):
        """Gets the customer_supplied_nodes of this NodePreCheckRequest.  # noqa: E501

        Customer supplied nodes  # noqa: E501

        :return: The customer_supplied_nodes of this NodePreCheckRequest.  # noqa: E501
        :rtype: list[CustomerSuppliedSpec]
        """
        return self._customer_supplied_nodes

    @customer_supplied_nodes.setter
    def customer_supplied_nodes(self, customer_supplied_nodes):
        """Sets the customer_supplied_nodes of this NodePreCheckRequest.

        Customer supplied nodes  # noqa: E501

        :param customer_supplied_nodes: The customer_supplied_nodes of this NodePreCheckRequest.  # noqa: E501
        :type: list[CustomerSuppliedSpec]
        """

        self._customer_supplied_nodes = customer_supplied_nodes

    @property
    def segment_label(self):
        """Gets the segment_label of this NodePreCheckRequest.  # noqa: E501

        The layer3 segment label  # noqa: E501

        :return: The segment_label of this NodePreCheckRequest.  # noqa: E501
        :rtype: str
        """
        return self._segment_label

    @segment_label.setter
    def segment_label(self, segment_label):
        """Sets the segment_label of this NodePreCheckRequest.

        The layer3 segment label  # noqa: E501

        :param segment_label: The segment_label of this NodePreCheckRequest.  # noqa: E501
        :type: str
        """

        self._segment_label = segment_label

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NodePreCheckRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NodePreCheckRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
