# coding: utf-8

"""
    VxRail Disk and Cluster Management

    APIs for disk and cluster management  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProxyNodeNetworkInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'netmask': 'str',
        'gateway': 'str',
        'vlan_id': 'int',
        'network_type': 'str'
    }

    attribute_map = {
        'netmask': 'netmask',
        'gateway': 'gateway',
        'vlan_id': 'vlan_id',
        'network_type': 'network_type'
    }

    def __init__(self, netmask=None, gateway=None, vlan_id=None, network_type=None):  # noqa: E501
        """ProxyNodeNetworkInfo - a model defined in Swagger"""  # noqa: E501
        self._netmask = None
        self._gateway = None
        self._vlan_id = None
        self._network_type = None
        self.discriminator = None
        self.netmask = netmask
        self.gateway = gateway
        self.vlan_id = vlan_id
        self.network_type = network_type

    @property
    def netmask(self):
        """Gets the netmask of this ProxyNodeNetworkInfo.  # noqa: E501


        :return: The netmask of this ProxyNodeNetworkInfo.  # noqa: E501
        :rtype: str
        """
        return self._netmask

    @netmask.setter
    def netmask(self, netmask):
        """Sets the netmask of this ProxyNodeNetworkInfo.


        :param netmask: The netmask of this ProxyNodeNetworkInfo.  # noqa: E501
        :type: str
        """
        if netmask is None:
            raise ValueError("Invalid value for `netmask`, must not be `None`")  # noqa: E501

        self._netmask = netmask

    @property
    def gateway(self):
        """Gets the gateway of this ProxyNodeNetworkInfo.  # noqa: E501


        :return: The gateway of this ProxyNodeNetworkInfo.  # noqa: E501
        :rtype: str
        """
        return self._gateway

    @gateway.setter
    def gateway(self, gateway):
        """Sets the gateway of this ProxyNodeNetworkInfo.


        :param gateway: The gateway of this ProxyNodeNetworkInfo.  # noqa: E501
        :type: str
        """
        if gateway is None:
            raise ValueError("Invalid value for `gateway`, must not be `None`")  # noqa: E501

        self._gateway = gateway

    @property
    def vlan_id(self):
        """Gets the vlan_id of this ProxyNodeNetworkInfo.  # noqa: E501


        :return: The vlan_id of this ProxyNodeNetworkInfo.  # noqa: E501
        :rtype: int
        """
        return self._vlan_id

    @vlan_id.setter
    def vlan_id(self, vlan_id):
        """Sets the vlan_id of this ProxyNodeNetworkInfo.


        :param vlan_id: The vlan_id of this ProxyNodeNetworkInfo.  # noqa: E501
        :type: int
        """
        if vlan_id is None:
            raise ValueError("Invalid value for `vlan_id`, must not be `None`")  # noqa: E501

        self._vlan_id = vlan_id

    @property
    def network_type(self):
        """Gets the network_type of this ProxyNodeNetworkInfo.  # noqa: E501


        :return: The network_type of this ProxyNodeNetworkInfo.  # noqa: E501
        :rtype: str
        """
        return self._network_type

    @network_type.setter
    def network_type(self, network_type):
        """Sets the network_type of this ProxyNodeNetworkInfo.


        :param network_type: The network_type of this ProxyNodeNetworkInfo.  # noqa: E501
        :type: str
        """
        if network_type is None:
            raise ValueError("Invalid value for `network_type`, must not be `None`")  # noqa: E501
        allowed_values = ["DIFF_SUBNET", "SAME_SUBNET"]  # noqa: E501
        if network_type not in allowed_values:
            raise ValueError(
                "Invalid value for `network_type` ({0}), must be one of {1}"  # noqa: E501
                .format(network_type, allowed_values)
            )

        self._network_type = network_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProxyNodeNetworkInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProxyNodeNetworkInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
